// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ProjectRoleAssignmentsInitParameters struct {
}

type ProjectRoleAssignmentsObservation struct {

	// Unique 24-hexadecimal digit string that identifies the project to which these roles belong.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// One or more project-level roles assigned to the MongoDB Cloud user.
	// +listType=set
	ProjectRoles []*string `json:"projectRoles,omitempty" tf:"project_roles,omitempty"`
}

type ProjectRoleAssignmentsParameters struct {
}

type RolesInitParameters struct {

	// One or more organization level roles to assign the MongoDB Cloud user.
	// +listType=set
	OrgRoles []*string `json:"orgRoles,omitempty" tf:"org_roles,omitempty"`
}

type RolesObservation struct {

	// One or more organization level roles to assign the MongoDB Cloud user.
	// +listType=set
	OrgRoles []*string `json:"orgRoles,omitempty" tf:"org_roles,omitempty"`

	ProjectRoleAssignments []ProjectRoleAssignmentsObservation `json:"projectRoleAssignments,omitempty" tf:"project_role_assignments,omitempty"`
}

type RolesParameters struct {

	// One or more organization level roles to assign the MongoDB Cloud user.
	// +kubebuilder:validation:Optional
	// +listType=set
	OrgRoles []*string `json:"orgRoles,omitempty" tf:"org_roles,omitempty"`
}

type UserOrgAssignmentInitParameters struct {

	// Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [/orgs](https://www.mongodb.com/docs/api/doc/atlas-admin-api-v2/group/endpoint-organizations) endpoint to retrieve all organizations to which the authenticated user has access.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-mongodbatlas/apis/cluster/global/v1alpha1.Organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in global to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.Reference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in global to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.Selector `json:"orgIdSelector,omitempty" tf:"-"`

	Roles *RolesInitParameters `json:"roles,omitempty" tf:"roles,omitempty"`

	// Email address that represents the username of the MongoDB Cloud user.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserOrgAssignmentObservation struct {

	// Two-character alphabetical string that identifies the MongoDB Cloud user's geographic location. This parameter uses the ISO 3166-1a2 code format.
	Country *string `json:"country,omitempty" tf:"country,omitempty"`

	// Date and time when MongoDB Cloud created the current account. This value is in the ISO 8601 timestamp format in UTC.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// First or given name that belongs to the MongoDB Cloud user.
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Date and time when MongoDB Cloud sent the invitation. MongoDB Cloud represents this timestamp in ISO 8601 format in UTC.
	InvitationCreatedAt *string `json:"invitationCreatedAt,omitempty" tf:"invitation_created_at,omitempty"`

	// Date and time when the invitation from MongoDB Cloud expires. MongoDB Cloud represents this timestamp in ISO 8601 format in UTC.
	InvitationExpiresAt *string `json:"invitationExpiresAt,omitempty" tf:"invitation_expires_at,omitempty"`

	// Username of the MongoDB Cloud user who sent the invitation to join the organization.
	InviterUsername *string `json:"inviterUsername,omitempty" tf:"inviter_username,omitempty"`

	// Date and time when the current account last authenticated. This value is in the ISO 8601 timestamp format in UTC.
	LastAuth *string `json:"lastAuth,omitempty" tf:"last_auth,omitempty"`

	// Last name, family name, or surname that belongs to the MongoDB Cloud user.
	LastName *string `json:"lastName,omitempty" tf:"last_name,omitempty"`

	// Mobile phone number that belongs to the MongoDB Cloud user.
	MobileNumber *string `json:"mobileNumber,omitempty" tf:"mobile_number,omitempty"`

	// Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [/orgs](https://www.mongodb.com/docs/api/doc/atlas-admin-api-v2/group/endpoint-organizations) endpoint to retrieve all organizations to which the authenticated user has access.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// String enum that indicates whether the MongoDB Cloud user has a pending invitation to join the organization or they are already active in the organization.
	OrgMembershipStatus *string `json:"orgMembershipStatus,omitempty" tf:"org_membership_status,omitempty"`

	Roles *RolesObservation `json:"roles,omitempty" tf:"roles,omitempty"`

	// List of unique 24-hexadecimal digit strings that identifies the teams to which this MongoDB Cloud user belongs.
	// +listType=set
	TeamIds []*string `json:"teamIds,omitempty" tf:"team_ids,omitempty"`

	// Unique 24-hexadecimal digit string that identifies the MongoDB Cloud user.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Email address that represents the username of the MongoDB Cloud user.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type UserOrgAssignmentParameters struct {

	// Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [/orgs](https://www.mongodb.com/docs/api/doc/atlas-admin-api-v2/group/endpoint-organizations) endpoint to retrieve all organizations to which the authenticated user has access.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-mongodbatlas/apis/cluster/global/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in global to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.Reference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in global to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.Selector `json:"orgIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Roles *RolesParameters `json:"roles,omitempty" tf:"roles,omitempty"`

	// Email address that represents the username of the MongoDB Cloud user.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// UserOrgAssignmentSpec defines the desired state of UserOrgAssignment
type UserOrgAssignmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserOrgAssignmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserOrgAssignmentInitParameters `json:"initProvider,omitempty"`
}

// UserOrgAssignmentStatus defines the observed state of UserOrgAssignment.
type UserOrgAssignmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserOrgAssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserOrgAssignment is the Schema for the UserOrgAssignments API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,mongodbatlas}
type UserOrgAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roles) || (has(self.initProvider) && has(self.initProvider.roles))",message="spec.forProvider.roles is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   UserOrgAssignmentSpec   `json:"spec"`
	Status UserOrgAssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserOrgAssignmentList contains a list of UserOrgAssignments
type UserOrgAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserOrgAssignment `json:"items"`
}

// Repository type metadata.
var (
	UserOrgAssignment_Kind             = "UserOrgAssignment"
	UserOrgAssignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserOrgAssignment_Kind}.String()
	UserOrgAssignment_KindAPIVersion   = UserOrgAssignment_Kind + "." + CRDGroupVersion.String()
	UserOrgAssignment_GroupVersionKind = CRDGroupVersion.WithKind(UserOrgAssignment_Kind)
)

func init() {
	SchemeBuilder.Register(&UserOrgAssignment{}, &UserOrgAssignmentList{})
}
