/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EndpointServiceServerlessObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	PrivateLinkServiceResourceID *string `json:"privateLinkServiceResourceId,omitempty" tf:"private_link_service_resource_id,omitempty"`

	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type EndpointServiceServerlessParameters struct {

	// +kubebuilder:validation:Optional
	CloudProviderEndpointID *string `json:"cloudProviderEndpointId,omitempty" tf:"cloud_provider_endpoint_id,omitempty"`

	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// +kubebuilder:validation:Required
	EndpointID *string `json:"endpointId" tf:"endpoint_id,omitempty"`

	// +kubebuilder:validation:Required
	InstanceName *string `json:"instanceName" tf:"instance_name,omitempty"`

	// +kubebuilder:validation:Optional
	PrivateEndpointIPAddress *string `json:"privateEndpointIpAddress,omitempty" tf:"private_endpoint_ip_address,omitempty"`

	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-mongodbatlas/apis/mongodbatlas/v1alpha1.Project
	// +crossplane:generate:reference:extractor=github.com/crossplane-contrib/provider-mongodbatlas/config/common.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in mongodbatlas to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in mongodbatlas to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Required
	ProviderName *string `json:"providerName" tf:"provider_name,omitempty"`
}

// EndpointServiceServerlessSpec defines the desired state of EndpointServiceServerless
type EndpointServiceServerlessSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EndpointServiceServerlessParameters `json:"forProvider"`
}

// EndpointServiceServerlessStatus defines the observed state of EndpointServiceServerless.
type EndpointServiceServerlessStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EndpointServiceServerlessObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// EndpointServiceServerless is the Schema for the EndpointServiceServerlesss API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,mongodbatlas}
type EndpointServiceServerless struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              EndpointServiceServerlessSpec   `json:"spec"`
	Status            EndpointServiceServerlessStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EndpointServiceServerlessList contains a list of EndpointServiceServerlesss
type EndpointServiceServerlessList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EndpointServiceServerless `json:"items"`
}

// Repository type metadata.
var (
	EndpointServiceServerless_Kind             = "EndpointServiceServerless"
	EndpointServiceServerless_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EndpointServiceServerless_Kind}.String()
	EndpointServiceServerless_KindAPIVersion   = EndpointServiceServerless_Kind + "." + CRDGroupVersion.String()
	EndpointServiceServerless_GroupVersionKind = CRDGroupVersion.WithKind(EndpointServiceServerless_Kind)
)

func init() {
	SchemeBuilder.Register(&EndpointServiceServerless{}, &EndpointServiceServerlessList{})
}
