apiVersion: mongodbatlas.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: mongodbtest1
spec:
  credentials:
    source: Secret
    secretRef:
      name: demo-creds
      namespace: crossplane-system
      key: credentials
