// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ConnectionFailoverAuthenticationInitParameters struct {

	// (String) OIDC client identifier for authentication to the Kafka cluster.
	// OIDC client identifier for authentication to the Kafka cluster.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String, Sensitive) OIDC client secret for authentication to the Kafka cluster.
	// OIDC client secret for authentication to the Kafka cluster.
	ClientSecretSecretRef *v2.SecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// 256, SCRAM-512, or OAUTHBEARER.
	// Style of authentication. Can be one of PLAIN, SCRAM-256, SCRAM-512, or OAUTHBEARER.
	Mechanism *string `json:"mechanism,omitempty" tf:"mechanism,omitempty"`

	// (String) SASL OAUTHBEARER authentication method. Currently, only OIDC is supported.
	// SASL OAUTHBEARER authentication method. Currently, only OIDC is supported.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// (String, Sensitive) Password of the account to connect to the Kafka cluster.
	// Password of the account to connect to the Kafka cluster.
	PasswordSecretRef *v2.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) SSL certificate for client authentication to Kafka.
	// SSL certificate for client authentication to Kafka.
	SSLCertificate *string `json:"sslCertificate,omitempty" tf:"ssl_certificate,omitempty"`

	// (String, Sensitive) Password for the SSL key, if it is password protected.
	// Password for the SSL key, if it is password protected.
	SSLKeyPasswordSecretRef *v2.SecretKeySelector `json:"sslKeyPasswordSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) SSL key for client authentication to Kafka.
	// SSL key for client authentication to Kafka.
	SSLKeySecretRef *v2.SecretKeySelector `json:"sslKeySecretRef,omitempty" tf:"-"`

	// (String) SASL OAUTHBEARER extensions parameter for additional OAuth2 configuration.
	// SASL OAUTHBEARER extensions parameter for additional OAuth2 configuration.
	SaslOauthbearerExtensions *string `json:"saslOauthbearerExtensions,omitempty" tf:"sasl_oauthbearer_extensions,omitempty"`

	// (String) OIDC scope parameter defining the access permissions requested.
	// OIDC scope parameter defining the access permissions requested.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) OIDC token endpoint URL for obtaining access tokens.
	// OIDC token endpoint URL for obtaining access tokens.
	TokenEndpointURL *string `json:"tokenEndpointUrl,omitempty" tf:"token_endpoint_url,omitempty"`

	// (String) Username of the account to connect to the Kafka cluster.
	// Username of the account to connect to the Kafka cluster.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ConnectionFailoverAuthenticationObservation struct {

	// (String) OIDC client identifier for authentication to the Kafka cluster.
	// OIDC client identifier for authentication to the Kafka cluster.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// 256, SCRAM-512, or OAUTHBEARER.
	// Style of authentication. Can be one of PLAIN, SCRAM-256, SCRAM-512, or OAUTHBEARER.
	Mechanism *string `json:"mechanism,omitempty" tf:"mechanism,omitempty"`

	// (String) SASL OAUTHBEARER authentication method. Currently, only OIDC is supported.
	// SASL OAUTHBEARER authentication method. Currently, only OIDC is supported.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// (String) SSL certificate for client authentication to Kafka.
	// SSL certificate for client authentication to Kafka.
	SSLCertificate *string `json:"sslCertificate,omitempty" tf:"ssl_certificate,omitempty"`

	// (String) SASL OAUTHBEARER extensions parameter for additional OAuth2 configuration.
	// SASL OAUTHBEARER extensions parameter for additional OAuth2 configuration.
	SaslOauthbearerExtensions *string `json:"saslOauthbearerExtensions,omitempty" tf:"sasl_oauthbearer_extensions,omitempty"`

	// (String) OIDC scope parameter defining the access permissions requested.
	// OIDC scope parameter defining the access permissions requested.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) OIDC token endpoint URL for obtaining access tokens.
	// OIDC token endpoint URL for obtaining access tokens.
	TokenEndpointURL *string `json:"tokenEndpointUrl,omitempty" tf:"token_endpoint_url,omitempty"`

	// (String) Username of the account to connect to the Kafka cluster.
	// Username of the account to connect to the Kafka cluster.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ConnectionFailoverAuthenticationParameters struct {

	// (String) OIDC client identifier for authentication to the Kafka cluster.
	// OIDC client identifier for authentication to the Kafka cluster.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String, Sensitive) OIDC client secret for authentication to the Kafka cluster.
	// OIDC client secret for authentication to the Kafka cluster.
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef *v2.SecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// 256, SCRAM-512, or OAUTHBEARER.
	// Style of authentication. Can be one of PLAIN, SCRAM-256, SCRAM-512, or OAUTHBEARER.
	// +kubebuilder:validation:Optional
	Mechanism *string `json:"mechanism,omitempty" tf:"mechanism,omitempty"`

	// (String) SASL OAUTHBEARER authentication method. Currently, only OIDC is supported.
	// SASL OAUTHBEARER authentication method. Currently, only OIDC is supported.
	// +kubebuilder:validation:Optional
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// (String, Sensitive) Password of the account to connect to the Kafka cluster.
	// Password of the account to connect to the Kafka cluster.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v2.SecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) SSL certificate for client authentication to Kafka.
	// SSL certificate for client authentication to Kafka.
	// +kubebuilder:validation:Optional
	SSLCertificate *string `json:"sslCertificate,omitempty" tf:"ssl_certificate,omitempty"`

	// (String, Sensitive) Password for the SSL key, if it is password protected.
	// Password for the SSL key, if it is password protected.
	// +kubebuilder:validation:Optional
	SSLKeyPasswordSecretRef *v2.SecretKeySelector `json:"sslKeyPasswordSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) SSL key for client authentication to Kafka.
	// SSL key for client authentication to Kafka.
	// +kubebuilder:validation:Optional
	SSLKeySecretRef *v2.SecretKeySelector `json:"sslKeySecretRef,omitempty" tf:"-"`

	// (String) SASL OAUTHBEARER extensions parameter for additional OAuth2 configuration.
	// SASL OAUTHBEARER extensions parameter for additional OAuth2 configuration.
	// +kubebuilder:validation:Optional
	SaslOauthbearerExtensions *string `json:"saslOauthbearerExtensions,omitempty" tf:"sasl_oauthbearer_extensions,omitempty"`

	// (String) OIDC scope parameter defining the access permissions requested.
	// OIDC scope parameter defining the access permissions requested.
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// (String) OIDC token endpoint URL for obtaining access tokens.
	// OIDC token endpoint URL for obtaining access tokens.
	// +kubebuilder:validation:Optional
	TokenEndpointURL *string `json:"tokenEndpointUrl,omitempty" tf:"token_endpoint_url,omitempty"`

	// (String) Username of the account to connect to the Kafka cluster.
	// Username of the account to connect to the Kafka cluster.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ConnectionFailoverDBRoleToExecuteInitParameters struct {

	// (String) The name of the role to use. Can be a built in role or a custom role.
	// The name of the role to use. Can be a built in role or a custom role.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// (String) Connection type.
	// Type of the DB role. Can be either Built In or Custom.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ConnectionFailoverDBRoleToExecuteObservation struct {

	// (String) The name of the role to use. Can be a built in role or a custom role.
	// The name of the role to use. Can be a built in role or a custom role.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// (String) Connection type.
	// Type of the DB role. Can be either Built In or Custom.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ConnectionFailoverDBRoleToExecuteParameters struct {

	// (String) The name of the role to use. Can be a built in role or a custom role.
	// The name of the role to use. Can be a built in role or a custom role.
	// +kubebuilder:validation:Optional
	Role *string `json:"role" tf:"role,omitempty"`

	// (String) Connection type.
	// Type of the DB role. Can be either Built In or Custom.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type ConnectionFailoverInitParameters struct {

	// (Attributes) User credentials required to connect to a Kafka Cluster. Includes the authentication type, as well as the parameters for that authentication mode. (see below for nested schema)
	Authentication *ConnectionFailoverAuthenticationInitParameters `json:"authentication,omitempty" tf:"authentication,omitempty"`

	// (String) Comma separated list of server addresses.
	// Optional for type: Kafka. Comma separated list of server addresses.
	BootstrapServers *string `json:"bootstrapServers,omitempty" tf:"bootstrap_servers,omitempty"`

	// (String) Name of the cluster configured for this connection.
	// Optional for type: Cluster. Name of the cluster configured for this connection.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// hexadecimal digit string that identifies the project that contains the configured cluster. Required if the ID does not match the project containing the streams workspace. You must first enable the organization setting.
	// Optional for type: Cluster. Unique 24-hexadecimal digit string that identifies the project that contains the configured cluster. Required if the ID does not match the project containing the streams workspace. You must first enable the organization setting.
	ClusterProjectID *string `json:"clusterProjectId,omitempty" tf:"cluster_project_id,omitempty"`

	// value pairs for optional configuration. This object is flat, and keys can have '.' characters.
	// Optional for type: Kafka. Map of Kafka key-value pairs for optional configuration. This object is flat, and keys can have '.' characters.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// (String) Label that identifies the stream connection name.
	// Label that identifies the stream connection name.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-mongodbatlas/apis/cluster/stream/v1alpha1.Connection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("connection_name",false)
	ConnectionName *string `json:"connectionName,omitempty" tf:"connection_name,omitempty"`

	// Reference to a Connection in stream to populate connectionName.
	// +kubebuilder:validation:Optional
	ConnectionNameRef *v2.Reference `json:"connectionNameRef,omitempty" tf:"-"`

	// Selector for a Connection in stream to populate connectionName.
	// +kubebuilder:validation:Optional
	ConnectionNameSelector *v2.Selector `json:"connectionNameSelector,omitempty" tf:"-"`

	// in or custom DB Role to connect to a MongoDB Cloud Cluster. (see below for nested schema)
	DBRoleToExecute *ConnectionFailoverDBRoleToExecuteInitParameters `json:"dbRoleToExecute,omitempty" tf:"db_role_to_execute,omitempty"`

	// (Boolean) Indicates whether to delete the resource being created if a timeout is reached when waiting for completion. When set to true and timeout occurs, it triggers the deletion and returns immediately without waiting for deletion to complete. When set to false, the timeout will not trigger resource deletion. If you suspect a transient error when the value is true, wait before retrying to allow resource deletion to finish. Default is true.
	// Indicates whether to delete the resource being created if a timeout is reached when waiting for completion. When set to `true` and timeout occurs, it triggers the deletion and returns immediately without waiting for deletion to complete. When set to `false`, the timeout will not trigger resource deletion. If you suspect a transient error when the value is `true`, wait before retrying to allow resource deletion to finish. Default is `true`.
	DeleteOnCreateTimeout *bool `json:"deleteOnCreateTimeout,omitempty" tf:"delete_on_create_timeout,omitempty"`

	// (Attributes) Networking configuration for Streams connections. (see below for nested schema)
	Networking *ConnectionFailoverNetworkingInitParameters `json:"networking,omitempty" tf:"networking,omitempty"`

	// hexadecimal digit string that identifies your project, also known as groupId in the official documentation.
	// Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-mongodbatlas/apis/cluster/mongodbatlas/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in mongodbatlas to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in mongodbatlas to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) Connection region.
	// Connection region.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Attributes) Properties for the secure transport connection to Kafka. For SSL, this can include the trusted certificate to use. (see below for nested schema)
	Security *ConnectionFailoverSecurityInitParameters `json:"security,omitempty" tf:"security,omitempty"`

	// (Attributes) (see below for nested schema)
	Timeouts *ConnectionFailoverTimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// (String) Connection type.
	// Connection type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Label that identifies the stream workspace.
	// Label that identifies the stream workspace.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-mongodbatlas/apis/cluster/stream/v1alpha1.Workspace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("workspace_name",false)
	WorkspaceName *string `json:"workspaceName,omitempty" tf:"workspace_name,omitempty"`

	// Reference to a Workspace in stream to populate workspaceName.
	// +kubebuilder:validation:Optional
	WorkspaceNameRef *v2.Reference `json:"workspaceNameRef,omitempty" tf:"-"`

	// Selector for a Workspace in stream to populate workspaceName.
	// +kubebuilder:validation:Optional
	WorkspaceNameSelector *v2.Selector `json:"workspaceNameSelector,omitempty" tf:"-"`
}

type ConnectionFailoverNetworkingInitParameters struct {

	// (Attributes) Information about networking access. (see below for nested schema)
	Access *NetworkingAccessInitParameters `json:"access,omitempty" tf:"access,omitempty"`
}

type ConnectionFailoverNetworkingObservation struct {

	// (Attributes) Information about networking access. (see below for nested schema)
	Access *NetworkingAccessObservation `json:"access,omitempty" tf:"access,omitempty"`
}

type ConnectionFailoverNetworkingParameters struct {

	// (Attributes) Information about networking access. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Access *NetworkingAccessParameters `json:"access,omitempty" tf:"access,omitempty"`
}

type ConnectionFailoverObservation struct {

	// (Attributes) User credentials required to connect to a Kafka Cluster. Includes the authentication type, as well as the parameters for that authentication mode. (see below for nested schema)
	Authentication *ConnectionFailoverAuthenticationObservation `json:"authentication,omitempty" tf:"authentication,omitempty"`

	// (String) Comma separated list of server addresses.
	// Optional for type: Kafka. Comma separated list of server addresses.
	BootstrapServers *string `json:"bootstrapServers,omitempty" tf:"bootstrap_servers,omitempty"`

	// (String) Name of the cluster configured for this connection.
	// Optional for type: Cluster. Name of the cluster configured for this connection.
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// hexadecimal digit string that identifies the project that contains the configured cluster. Required if the ID does not match the project containing the streams workspace. You must first enable the organization setting.
	// Optional for type: Cluster. Unique 24-hexadecimal digit string that identifies the project that contains the configured cluster. Required if the ID does not match the project containing the streams workspace. You must first enable the organization setting.
	ClusterProjectID *string `json:"clusterProjectId,omitempty" tf:"cluster_project_id,omitempty"`

	// value pairs for optional configuration. This object is flat, and keys can have '.' characters.
	// Optional for type: Kafka. Map of Kafka key-value pairs for optional configuration. This object is flat, and keys can have '.' characters.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// (String) Label that identifies the stream connection name.
	// Label that identifies the stream connection name.
	ConnectionName *string `json:"connectionName,omitempty" tf:"connection_name,omitempty"`

	// in or custom DB Role to connect to a MongoDB Cloud Cluster. (see below for nested schema)
	DBRoleToExecute *ConnectionFailoverDBRoleToExecuteObservation `json:"dbRoleToExecute,omitempty" tf:"db_role_to_execute,omitempty"`

	// (Boolean) Indicates whether to delete the resource being created if a timeout is reached when waiting for completion. When set to true and timeout occurs, it triggers the deletion and returns immediately without waiting for deletion to complete. When set to false, the timeout will not trigger resource deletion. If you suspect a transient error when the value is true, wait before retrying to allow resource deletion to finish. Default is true.
	// Indicates whether to delete the resource being created if a timeout is reached when waiting for completion. When set to `true` and timeout occurs, it triggers the deletion and returns immediately without waiting for deletion to complete. When set to `false`, the timeout will not trigger resource deletion. If you suspect a transient error when the value is `true`, wait before retrying to allow resource deletion to finish. Default is `true`.
	DeleteOnCreateTimeout *bool `json:"deleteOnCreateTimeout,omitempty" tf:"delete_on_create_timeout,omitempty"`

	// (String) Unique identifier of the connection.
	// Unique identifier of the connection.
	FailoverConnectionID *string `json:"failoverConnectionId,omitempty" tf:"failover_connection_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) Networking configuration for Streams connections. (see below for nested schema)
	Networking *ConnectionFailoverNetworkingObservation `json:"networking,omitempty" tf:"networking,omitempty"`

	// hexadecimal digit string that identifies your project, also known as groupId in the official documentation.
	// Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) Connection region.
	// Connection region.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Attributes) Properties for the secure transport connection to Kafka. For SSL, this can include the trusted certificate to use. (see below for nested schema)
	Security *ConnectionFailoverSecurityObservation `json:"security,omitempty" tf:"security,omitempty"`

	// (String) Connection state.
	// Connection state.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (Attributes) (see below for nested schema)
	Timeouts *ConnectionFailoverTimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// (String) Connection type.
	// Connection type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Label that identifies the stream workspace.
	// Label that identifies the stream workspace.
	WorkspaceName *string `json:"workspaceName,omitempty" tf:"workspace_name,omitempty"`
}

type ConnectionFailoverParameters struct {

	// (Attributes) User credentials required to connect to a Kafka Cluster. Includes the authentication type, as well as the parameters for that authentication mode. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Authentication *ConnectionFailoverAuthenticationParameters `json:"authentication,omitempty" tf:"authentication,omitempty"`

	// (String) Comma separated list of server addresses.
	// Optional for type: Kafka. Comma separated list of server addresses.
	// +kubebuilder:validation:Optional
	BootstrapServers *string `json:"bootstrapServers,omitempty" tf:"bootstrap_servers,omitempty"`

	// (String) Name of the cluster configured for this connection.
	// Optional for type: Cluster. Name of the cluster configured for this connection.
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// hexadecimal digit string that identifies the project that contains the configured cluster. Required if the ID does not match the project containing the streams workspace. You must first enable the organization setting.
	// Optional for type: Cluster. Unique 24-hexadecimal digit string that identifies the project that contains the configured cluster. Required if the ID does not match the project containing the streams workspace. You must first enable the organization setting.
	// +kubebuilder:validation:Optional
	ClusterProjectID *string `json:"clusterProjectId,omitempty" tf:"cluster_project_id,omitempty"`

	// value pairs for optional configuration. This object is flat, and keys can have '.' characters.
	// Optional for type: Kafka. Map of Kafka key-value pairs for optional configuration. This object is flat, and keys can have '.' characters.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// (String) Label that identifies the stream connection name.
	// Label that identifies the stream connection name.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-mongodbatlas/apis/cluster/stream/v1alpha1.Connection
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("connection_name",false)
	// +kubebuilder:validation:Optional
	ConnectionName *string `json:"connectionName,omitempty" tf:"connection_name,omitempty"`

	// Reference to a Connection in stream to populate connectionName.
	// +kubebuilder:validation:Optional
	ConnectionNameRef *v2.Reference `json:"connectionNameRef,omitempty" tf:"-"`

	// Selector for a Connection in stream to populate connectionName.
	// +kubebuilder:validation:Optional
	ConnectionNameSelector *v2.Selector `json:"connectionNameSelector,omitempty" tf:"-"`

	// in or custom DB Role to connect to a MongoDB Cloud Cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	DBRoleToExecute *ConnectionFailoverDBRoleToExecuteParameters `json:"dbRoleToExecute,omitempty" tf:"db_role_to_execute,omitempty"`

	// (Boolean) Indicates whether to delete the resource being created if a timeout is reached when waiting for completion. When set to true and timeout occurs, it triggers the deletion and returns immediately without waiting for deletion to complete. When set to false, the timeout will not trigger resource deletion. If you suspect a transient error when the value is true, wait before retrying to allow resource deletion to finish. Default is true.
	// Indicates whether to delete the resource being created if a timeout is reached when waiting for completion. When set to `true` and timeout occurs, it triggers the deletion and returns immediately without waiting for deletion to complete. When set to `false`, the timeout will not trigger resource deletion. If you suspect a transient error when the value is `true`, wait before retrying to allow resource deletion to finish. Default is `true`.
	// +kubebuilder:validation:Optional
	DeleteOnCreateTimeout *bool `json:"deleteOnCreateTimeout,omitempty" tf:"delete_on_create_timeout,omitempty"`

	// (Attributes) Networking configuration for Streams connections. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Networking *ConnectionFailoverNetworkingParameters `json:"networking,omitempty" tf:"networking,omitempty"`

	// hexadecimal digit string that identifies your project, also known as groupId in the official documentation.
	// Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-mongodbatlas/apis/cluster/mongodbatlas/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in mongodbatlas to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v2.Reference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in mongodbatlas to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v2.Selector `json:"projectIdSelector,omitempty" tf:"-"`

	// (String) Connection region.
	// Connection region.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Attributes) Properties for the secure transport connection to Kafka. For SSL, this can include the trusted certificate to use. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Security *ConnectionFailoverSecurityParameters `json:"security,omitempty" tf:"security,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Timeouts *ConnectionFailoverTimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// (String) Connection type.
	// Connection type.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Label that identifies the stream workspace.
	// Label that identifies the stream workspace.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-mongodbatlas/apis/cluster/stream/v1alpha1.Workspace
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("workspace_name",false)
	// +kubebuilder:validation:Optional
	WorkspaceName *string `json:"workspaceName,omitempty" tf:"workspace_name,omitempty"`

	// Reference to a Workspace in stream to populate workspaceName.
	// +kubebuilder:validation:Optional
	WorkspaceNameRef *v2.Reference `json:"workspaceNameRef,omitempty" tf:"-"`

	// Selector for a Workspace in stream to populate workspaceName.
	// +kubebuilder:validation:Optional
	WorkspaceNameSelector *v2.Selector `json:"workspaceNameSelector,omitempty" tf:"-"`
}

type ConnectionFailoverSecurityInitParameters struct {

	// (String) A trusted, public x509 certificate for connecting to Kafka over SSL.
	// A trusted, public x509 certificate for connecting to Kafka over SSL.
	BrokerPublicCertificate *string `json:"brokerPublicCertificate,omitempty" tf:"broker_public_certificate,omitempty"`

	// (String) Describes the transport type. Can be either SASL_PLAINTEXT, SASL_SSL, or SSL.
	// Describes the transport type. Can be either `SASL_PLAINTEXT`, `SASL_SSL`, or `SSL`.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type ConnectionFailoverSecurityObservation struct {

	// (String) A trusted, public x509 certificate for connecting to Kafka over SSL.
	// A trusted, public x509 certificate for connecting to Kafka over SSL.
	BrokerPublicCertificate *string `json:"brokerPublicCertificate,omitempty" tf:"broker_public_certificate,omitempty"`

	// (String) Describes the transport type. Can be either SASL_PLAINTEXT, SASL_SSL, or SSL.
	// Describes the transport type. Can be either `SASL_PLAINTEXT`, `SASL_SSL`, or `SSL`.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type ConnectionFailoverSecurityParameters struct {

	// (String) A trusted, public x509 certificate for connecting to Kafka over SSL.
	// A trusted, public x509 certificate for connecting to Kafka over SSL.
	// +kubebuilder:validation:Optional
	BrokerPublicCertificate *string `json:"brokerPublicCertificate,omitempty" tf:"broker_public_certificate,omitempty"`

	// (String) Describes the transport type. Can be either SASL_PLAINTEXT, SASL_SSL, or SSL.
	// Describes the transport type. Can be either `SASL_PLAINTEXT`, `SASL_SSL`, or `SSL`.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type ConnectionFailoverTimeoutsInitParameters struct {

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type ConnectionFailoverTimeoutsObservation struct {

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type ConnectionFailoverTimeoutsParameters struct {

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// (String) A string that can be parsed as a duration consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type NetworkingAccessInitParameters struct {

	// (String) Reserved. Will be used by PRIVATE_LINK connection type.
	// Reserved. Will be used by `PRIVATE_LINK` connection type.
	ConnectionID *string `json:"connectionId,omitempty" tf:"connection_id,omitempty"`

	// (String) Reserved. Will be used by PRIVATE_LINK connection type.
	// Reserved. Will be used by `PRIVATE_LINK` connection type.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Reserved. Will be used by TRANSIT_GATEWAY connection type.
	// Reserved. Will be used by `TRANSIT_GATEWAY` connection type.
	TgwRouteID *string `json:"tgwRouteId,omitempty" tf:"tgw_route_id,omitempty"`

	// (String) Connection type.
	// Selected networking type. Either `PUBLIC`, `VPC`, `PRIVATE_LINK`, or `TRANSIT_GATEWAY`. Defaults to `PUBLIC`. For VPC, ensure that VPC peering exists and connectivity has been established between Atlas VPC and the VPC where Kafka cluster is hosted for the connection to function properly. `TRANSIT_GATEWAY` support is coming soon.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type NetworkingAccessObservation struct {

	// (String) Reserved. Will be used by PRIVATE_LINK connection type.
	// Reserved. Will be used by `PRIVATE_LINK` connection type.
	ConnectionID *string `json:"connectionId,omitempty" tf:"connection_id,omitempty"`

	// (String) Reserved. Will be used by PRIVATE_LINK connection type.
	// Reserved. Will be used by `PRIVATE_LINK` connection type.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Reserved. Will be used by TRANSIT_GATEWAY connection type.
	// Reserved. Will be used by `TRANSIT_GATEWAY` connection type.
	TgwRouteID *string `json:"tgwRouteId,omitempty" tf:"tgw_route_id,omitempty"`

	// (String) Connection type.
	// Selected networking type. Either `PUBLIC`, `VPC`, `PRIVATE_LINK`, or `TRANSIT_GATEWAY`. Defaults to `PUBLIC`. For VPC, ensure that VPC peering exists and connectivity has been established between Atlas VPC and the VPC where Kafka cluster is hosted for the connection to function properly. `TRANSIT_GATEWAY` support is coming soon.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type NetworkingAccessParameters struct {

	// (String) Reserved. Will be used by PRIVATE_LINK connection type.
	// Reserved. Will be used by `PRIVATE_LINK` connection type.
	// +kubebuilder:validation:Optional
	ConnectionID *string `json:"connectionId,omitempty" tf:"connection_id,omitempty"`

	// (String) Reserved. Will be used by PRIVATE_LINK connection type.
	// Reserved. Will be used by `PRIVATE_LINK` connection type.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Reserved. Will be used by TRANSIT_GATEWAY connection type.
	// Reserved. Will be used by `TRANSIT_GATEWAY` connection type.
	// +kubebuilder:validation:Optional
	TgwRouteID *string `json:"tgwRouteId,omitempty" tf:"tgw_route_id,omitempty"`

	// (String) Connection type.
	// Selected networking type. Either `PUBLIC`, `VPC`, `PRIVATE_LINK`, or `TRANSIT_GATEWAY`. Defaults to `PUBLIC`. For VPC, ensure that VPC peering exists and connectivity has been established between Atlas VPC and the VPC where Kafka cluster is hosted for the connection to function properly. `TRANSIT_GATEWAY` support is coming soon.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ConnectionFailoverSpec defines the desired state of ConnectionFailover
type ConnectionFailoverSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ConnectionFailoverParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConnectionFailoverInitParameters `json:"initProvider,omitempty"`
}

// ConnectionFailoverStatus defines the observed state of ConnectionFailover.
type ConnectionFailoverStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ConnectionFailoverObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ConnectionFailover is the Schema for the ConnectionFailovers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,mongodbatlas}
type ConnectionFailover struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ConnectionFailoverSpec   `json:"spec"`
	Status ConnectionFailoverStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConnectionFailoverList contains a list of ConnectionFailovers
type ConnectionFailoverList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConnectionFailover `json:"items"`
}

// Repository type metadata.
var (
	ConnectionFailover_Kind             = "ConnectionFailover"
	ConnectionFailover_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ConnectionFailover_Kind}.String()
	ConnectionFailover_KindAPIVersion   = ConnectionFailover_Kind + "." + CRDGroupVersion.String()
	ConnectionFailover_GroupVersionKind = CRDGroupVersion.WithKind(ConnectionFailover_Kind)
)

func init() {
	SchemeBuilder.Register(&ConnectionFailover{}, &ConnectionFailoverList{})
}
