apiVersion: mongodbatlas.m.crossplane.io/v1alpha1
kind: CustomDNSConfigurationClusterAWS
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1alpha1/customdnsconfigurationclusteraws
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    enabled: true
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
