apiVersion: mongodbatlas.m.crossplane.io/v1alpha1
kind: LogIntegration
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1alpha1/logintegration
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    bucketName: ${aws_s3_bucket.log_bucket.bucket}
    iamRoleId: ${mongodbatlas_cloud_provider_access_authorization.auth.role_id}
    logTypes:
    - MONGOD_AUDIT
    prefixPath: atlas-logs
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: project
    type: S3_LOG_EXPORT

---

apiVersion: cloud.mongodbatlas.m.crossplane.io/v1alpha1
kind: ProviderAccessAuthorization
metadata:
  annotations:
    meta.upbound.io/example-id: /v1alpha1/logintegration
  labels:
    testing.upbound.io/example-name: auth
  name: auth
  namespace: crossplane-system
spec:
  forProvider:
    aws:
    - iamAssumedRoleArn: ${aws_iam_role.atlas_role.arn}
    projectId: ${mongodbatlas_project.project.id}
    roleId: ${mongodbatlas_cloud_provider_access_setup.setup.role_id}

---

apiVersion: cloud.mongodbatlas.m.crossplane.io/v1alpha1
kind: ProviderAccessSetup
metadata:
  annotations:
    meta.upbound.io/example-id: /v1alpha1/logintegration
  labels:
    testing.upbound.io/example-name: setup
  name: setup
  namespace: crossplane-system
spec:
  forProvider:
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: project
    providerName: AWS
