apiVersion: stream.mongodbatlas.m.crossplane.io/v1alpha1
kind: Connection
metadata:
  annotations:
    meta.upbound.io/example-id: stream/v1alpha1/connection
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    clusterName: Cluster0
    connectionName: ConnectionName
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    type: Cluster
    workspaceName: WorkspaceName
