apiVersion: stream.mongodbatlas.m.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: stream/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    dataProcessRegion:
      cloudProvider: AWS
      region: VIRGINIA_USA
    instanceName: InstanceName
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
