// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ActionsInitParameters struct {
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	Resources []ResourcesInitParameters `json:"resources,omitempty" tf:"resources,omitempty"`
}

type ActionsObservation struct {
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	Resources []ResourcesObservation `json:"resources,omitempty" tf:"resources,omitempty"`
}

type ActionsParameters struct {

	// +kubebuilder:validation:Optional
	Action *string `json:"action" tf:"action,omitempty"`

	// +kubebuilder:validation:Optional
	Resources []ResourcesParameters `json:"resources" tf:"resources,omitempty"`
}

type CustomRoleInitParameters struct {
	Actions []ActionsInitParameters `json:"actions,omitempty" tf:"actions,omitempty"`

	InheritedRoles []InheritedRolesInitParameters `json:"inheritedRoles,omitempty" tf:"inherited_roles,omitempty"`

	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-mongodbatlas/apis/namespaced/mongodbatlas/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in mongodbatlas to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in mongodbatlas to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

type CustomRoleObservation struct {
	Actions []ActionsObservation `json:"actions,omitempty" tf:"actions,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	InheritedRoles []InheritedRolesObservation `json:"inheritedRoles,omitempty" tf:"inherited_roles,omitempty"`

	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

type CustomRoleParameters struct {

	// +kubebuilder:validation:Optional
	Actions []ActionsParameters `json:"actions,omitempty" tf:"actions,omitempty"`

	// +kubebuilder:validation:Optional
	InheritedRoles []InheritedRolesParameters `json:"inheritedRoles,omitempty" tf:"inherited_roles,omitempty"`

	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-mongodbatlas/apis/namespaced/mongodbatlas/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in mongodbatlas to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in mongodbatlas to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

type InheritedRolesInitParameters struct {
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

type InheritedRolesObservation struct {
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	RoleName *string `json:"roleName,omitempty" tf:"role_name,omitempty"`
}

type InheritedRolesParameters struct {

	// +kubebuilder:validation:Optional
	DatabaseName *string `json:"databaseName" tf:"database_name,omitempty"`

	// +kubebuilder:validation:Optional
	RoleName *string `json:"roleName" tf:"role_name,omitempty"`
}

type ResourcesInitParameters struct {
	Cluster *bool `json:"cluster,omitempty" tf:"cluster,omitempty"`

	CollectionName *string `json:"collectionName,omitempty" tf:"collection_name,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`
}

type ResourcesObservation struct {
	Cluster *bool `json:"cluster,omitempty" tf:"cluster,omitempty"`

	CollectionName *string `json:"collectionName,omitempty" tf:"collection_name,omitempty"`

	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`
}

type ResourcesParameters struct {

	// +kubebuilder:validation:Optional
	Cluster *bool `json:"cluster,omitempty" tf:"cluster,omitempty"`

	// +kubebuilder:validation:Optional
	CollectionName *string `json:"collectionName,omitempty" tf:"collection_name,omitempty"`

	// +kubebuilder:validation:Optional
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`
}

// CustomRoleSpec defines the desired state of CustomRole
type CustomRoleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CustomRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CustomRoleInitParameters `json:"initProvider,omitempty"`
}

// CustomRoleStatus defines the observed state of CustomRole.
type CustomRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CustomRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CustomRole is the Schema for the CustomRoles API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,mongodbatlas}
type CustomRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roleName) || (has(self.initProvider) && has(self.initProvider.roleName))",message="spec.forProvider.roleName is a required parameter"
	Spec   CustomRoleSpec   `json:"spec"`
	Status CustomRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomRoleList contains a list of CustomRoles
type CustomRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomRole `json:"items"`
}

// Repository type metadata.
var (
	CustomRole_Kind             = "CustomRole"
	CustomRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomRole_Kind}.String()
	CustomRole_KindAPIVersion   = CustomRole_Kind + "." + CRDGroupVersion.String()
	CustomRole_GroupVersionKind = CRDGroupVersion.WithKind(CustomRole_Kind)
)

func init() {
	SchemeBuilder.Register(&CustomRole{}, &CustomRoleList{})
}
