apiVersion: federated.mongodbatlas.m.crossplane.io/v1alpha1
kind: PrivateLinkEndpointService
metadata:
  annotations:
    meta.upbound.io/example-id: federated/v1alpha1/privatelinkendpointservice
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: crossplane-system
spec:
  forProvider:
    comment: Test
    customerEndpointDnsName: ${aws_vpc_endpoint.test.dns_entry[0].dns_name}
    endpointId: ${aws_vpc_endpoint.test.id}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: atlas-project
    providerName: AWS
    region: US_EAST_1

---

apiVersion: mongodbatlas.m.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: federated/v1alpha1/privatelinkendpointservice
  labels:
    testing.upbound.io/example-name: atlas-project
  name: atlas-project
  namespace: crossplane-system
spec:
  forProvider:
    name: ${var.atlas_project_name}
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
