apiVersion: project.mongodbatlas.crossplane.io/v1alpha1
kind: ServiceAccountSecret
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/serviceaccountsecret
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    clientId: ${mongodbatlas_project_service_account.this.client_id}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secretExpiresAfterHours: 2160

---

apiVersion: project.mongodbatlas.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: project/v1alpha1/serviceaccountsecret
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    description: Example Project Service Account
    name: example-project-service-account
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    roles:
    - GROUP_READ_ONLY
    secretExpiresAfterHours: 2160
