apiVersion: mongodbatlas.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1alpha1/serviceaccount
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    description: Example Service Account
    name: example-service-account
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    roles:
    - ORG_READ_ONLY
    secretExpiresAfterHours: 2160
