apiVersion: mongodbatlas.crossplane.io/v1alpha1
kind: ServiceAccountProjectAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1alpha1/serviceaccountprojectassignment
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    clientId: ${mongodbatlas_service_account.this.client_id}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    roles:
    - GROUP_READ_ONLY

---

apiVersion: mongodbatlas.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: /v1alpha1/serviceaccountprojectassignment
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    description: Example Service Account
    name: example-service-account
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    roles:
    - ORG_MEMBER
    secretExpiresAfterHours: 2160
