apiVersion: mongodbatlas.crossplane.io/v1alpha1
kind: ServiceAccountAccessListEntry
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1alpha1/serviceaccountaccesslistentry
  labels:
    testing.upbound.io/example-name: cidr
  name: cidr
spec:
  forProvider:
    cidrBlock: 1.2.3.4/32
    clientId: ${mongodbatlas_service_account.this.client_id}
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: mongodbatlas.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: /v1alpha1/serviceaccountaccesslistentry
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    description: Example Service Account
    name: example-service-account
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    roles:
    - ORG_READ_ONLY
    secretExpiresAfterHours: 2160
