// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CreatedByUserInitParameters struct {
}

type CreatedByUserObservation struct {

	// Unique 24-hexadecimal character string that identifies a user.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Human-readable label that describes a user.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type CreatedByUserParameters struct {
}

type LastUpdatedByUserInitParameters struct {
}

type LastUpdatedByUserObservation struct {

	// Unique 24-hexadecimal character string that identifies a user.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Human-readable label that describes a user.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type LastUpdatedByUserParameters struct {
}

type PoliciesInitParameters struct {

	// A string that defines the permissions for the policy. The syntax used is the Cedar Policy language.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`
}

type PoliciesObservation struct {

	// A string that defines the permissions for the policy. The syntax used is the Cedar Policy language.
	Body *string `json:"body,omitempty" tf:"body,omitempty"`

	// Unique 24-hexadecimal character string that identifies the policy.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type PoliciesParameters struct {

	// A string that defines the permissions for the policy. The syntax used is the Cedar Policy language.
	// +kubebuilder:validation:Optional
	Body *string `json:"body" tf:"body,omitempty"`
}

type PolicyInitParameters struct {

	// Description of the Atlas resource policy.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Human-readable label that describes the Atlas resource policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [/orgs](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	Policies []PoliciesInitParameters `json:"policies,omitempty" tf:"policies,omitempty"`
}

type PolicyObservation struct {
	CreatedByUser *CreatedByUserObservation `json:"createdByUser,omitempty" tf:"created_by_user,omitempty"`

	// Date and time in UTC when the Atlas resource policy was created.
	CreatedDate *string `json:"createdDate,omitempty" tf:"created_date,omitempty"`

	// Description of the Atlas resource policy.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	LastUpdatedByUser *LastUpdatedByUserObservation `json:"lastUpdatedByUser,omitempty" tf:"last_updated_by_user,omitempty"`

	// Date and time in UTC when the Atlas resource policy was last updated.
	LastUpdatedDate *string `json:"lastUpdatedDate,omitempty" tf:"last_updated_date,omitempty"`

	// Human-readable label that describes the Atlas resource policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [/orgs](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	Policies []PoliciesObservation `json:"policies,omitempty" tf:"policies,omitempty"`

	// A string that identifies the version of the Atlas resource policy.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type PolicyParameters struct {

	// Description of the Atlas resource policy.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Human-readable label that describes the Atlas resource policy.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [/orgs](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// +kubebuilder:validation:Optional
	Policies []PoliciesParameters `json:"policies,omitempty" tf:"policies,omitempty"`
}

// PolicySpec defines the desired state of Policy
type PolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyInitParameters `json:"initProvider,omitempty"`
}

// PolicyStatus defines the observed state of Policy.
type PolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Policy is the Schema for the Policys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,mongodbatlas}
type Policy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.orgId) || (has(self.initProvider) && has(self.initProvider.orgId))",message="spec.forProvider.orgId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.policies) || (has(self.initProvider) && has(self.initProvider.policies))",message="spec.forProvider.policies is a required parameter"
	Spec   PolicySpec   `json:"spec"`
	Status PolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyList contains a list of Policys
type PolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Policy `json:"items"`
}

// Repository type metadata.
var (
	Policy_Kind             = "Policy"
	Policy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Policy_Kind}.String()
	Policy_KindAPIVersion   = Policy_Kind + "." + CRDGroupVersion.String()
	Policy_GroupVersionKind = CRDGroupVersion.WithKind(Policy_Kind)
)

func init() {
	SchemeBuilder.Register(&Policy{}, &PolicyList{})
}
