apiVersion: metric.mongodbatlas.crossplane.io/v1alpha1
kind: Integration
metadata:
  annotations:
    meta.upbound.io/example-id: metric/v1alpha1/integration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    aggregationTemporality: DELTA
    authType: HEADER
    endpoint: ${var.datadog_endpoint}
    headers:
    - name: dd-api-key
      valueSecretRef:
        key: attribute.key
        name: example-api-key
        namespace: crossplane-system
    integrationType: OTEL
    metricSelection:
    - ATLAS_STREAM_PROCESSING
    projectId: ${mongodbatlas_project.project.id}
    providerType: CUSTOM
