apiVersion: project.mongodbatlas.jet.crossplane.io/v1alpha1
kind: IPAccessList
metadata:
  name: test
spec:
  forProvider:
    cidrBlock: 18.117.85.64/32
    comment: test IP access list
    projectId: "6371cf3dad702f22e73d9fea"
  providerConfigRef:
    name: mongodbtest
