apiVersion: database.mongodbatlas.jet.crossplane.io/v1alpha2
kind: User
metadata:
  name: donuser2
spec:
  forProvider:
    authDatabaseName: admin
    passwordSecretRef:
      name: temp-creds
      namespace: crossplane-system
      key: password
    projectIdRef:
      name: test-project
    roles:
      - databaseName: dondb
        roleName: readWrite
    scopes:
      - name: test-cluster
        type: CLUSTER
  providerConfigRef:
    name: mongodbtest1