apiVersion: database.mongodbatlas.jet.crossplane.io/v1alpha2
kind: User
metadata:
  name: example
spec:
  forProvider:
    authDatabaseName: admin
    passwordSecretRef:
      name: user-password
      key: password
      namespace: crossplane-system
    projectIdRef:
      name: example-project
    roles:
      - databaseName: admin
        roleName: readAnyDatabase
    scopes:
      - name: test-scope
        type: CLUSTER
  providerConfigRef:
    name: default